server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdtempresas?useSSL=false
    username: root
    password: root6Beer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create